
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./componentes/Navbar";
import Sidebar from "./componentes/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  


  return (
    <html lang="en" data-theme="cupcake">
      <body className="h-full">
        <div className="flex items-center h-screen">
          {/* left section start */}
          <div className="w-[13%] h-screen">
            {/* Sidebar section start */}
            <Sidebar></Sidebar>
            {/* Sidebar section end */}
          </div>
          {/* left section end */}
          {/* right section start */}
          <div className="w-[87%] h-full">
            {/* navbar section start */}

              <Navbar></Navbar>
            {/* navbar section end */}
            {/* main content section start */}
              {children}
            {/* main content section end */}
          </div>
          {/* right section end */}
          
        </div>
      </body>
    </html>
  );
}
